// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: FinancialData.proto

package com.yyy.dailycode.enjoycoding.protocolbuffer.vo;

public final class FinancialDataModel {
  private FinancialDataModel() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface FinancialDataOrBuilder extends
      // @@protoc_insertion_point(interface_extends:FinancialData)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *营业收入
     * </pre>
     *
     * <code>string revenue = 1;</code>
     */
    java.lang.String getRevenue();
    /**
     * <pre>
     *营业收入
     * </pre>
     *
     * <code>string revenue = 1;</code>
     */
    com.google.protobuf.ByteString
        getRevenueBytes();

    /**
     * <pre>
     *净利润
     * </pre>
     *
     * <code>string netprofit = 2;</code>
     */
    java.lang.String getNetprofit();
    /**
     * <pre>
     *净利润
     * </pre>
     *
     * <code>string netprofit = 2;</code>
     */
    com.google.protobuf.ByteString
        getNetprofitBytes();

    /**
     * <pre>
     *营业收入增长率
     * </pre>
     *
     * <code>string revenuerose = 3;</code>
     */
    java.lang.String getRevenuerose();
    /**
     * <pre>
     *营业收入增长率
     * </pre>
     *
     * <code>string revenuerose = 3;</code>
     */
    com.google.protobuf.ByteString
        getRevenueroseBytes();

    /**
     * <pre>
     *净利润增长率
     * </pre>
     *
     * <code>string netprofitrose = 4;</code>
     */
    java.lang.String getNetprofitrose();
    /**
     * <pre>
     *净利润增长率
     * </pre>
     *
     * <code>string netprofitrose = 4;</code>
     */
    com.google.protobuf.ByteString
        getNetprofitroseBytes();
  }
  /**
   * <pre>
   *财务信息
   * </pre>
   *
   * Protobuf type {@code FinancialData}
   */
  public  static final class FinancialData extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:FinancialData)
      FinancialDataOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use FinancialData.newBuilder() to construct.
    private FinancialData(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private FinancialData() {
      revenue_ = "";
      netprofit_ = "";
      revenuerose_ = "";
      netprofitrose_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private FinancialData(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              revenue_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              netprofit_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              revenuerose_ = s;
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              netprofitrose_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.yyy.dailycode.enjoycoding.protocolbuffer.vo.FinancialDataModel.internal_static_FinancialData_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.yyy.dailycode.enjoycoding.protocolbuffer.vo.FinancialDataModel.internal_static_FinancialData_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.yyy.dailycode.enjoycoding.protocolbuffer.vo.FinancialDataModel.FinancialData.class, com.yyy.dailycode.enjoycoding.protocolbuffer.vo.FinancialDataModel.FinancialData.Builder.class);
    }

    public static final int REVENUE_FIELD_NUMBER = 1;
    private volatile java.lang.Object revenue_;
    /**
     * <pre>
     *营业收入
     * </pre>
     *
     * <code>string revenue = 1;</code>
     */
    public java.lang.String getRevenue() {
      java.lang.Object ref = revenue_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        revenue_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *营业收入
     * </pre>
     *
     * <code>string revenue = 1;</code>
     */
    public com.google.protobuf.ByteString
        getRevenueBytes() {
      java.lang.Object ref = revenue_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        revenue_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int NETPROFIT_FIELD_NUMBER = 2;
    private volatile java.lang.Object netprofit_;
    /**
     * <pre>
     *净利润
     * </pre>
     *
     * <code>string netprofit = 2;</code>
     */
    public java.lang.String getNetprofit() {
      java.lang.Object ref = netprofit_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        netprofit_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *净利润
     * </pre>
     *
     * <code>string netprofit = 2;</code>
     */
    public com.google.protobuf.ByteString
        getNetprofitBytes() {
      java.lang.Object ref = netprofit_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        netprofit_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int REVENUEROSE_FIELD_NUMBER = 3;
    private volatile java.lang.Object revenuerose_;
    /**
     * <pre>
     *营业收入增长率
     * </pre>
     *
     * <code>string revenuerose = 3;</code>
     */
    public java.lang.String getRevenuerose() {
      java.lang.Object ref = revenuerose_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        revenuerose_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *营业收入增长率
     * </pre>
     *
     * <code>string revenuerose = 3;</code>
     */
    public com.google.protobuf.ByteString
        getRevenueroseBytes() {
      java.lang.Object ref = revenuerose_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        revenuerose_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int NETPROFITROSE_FIELD_NUMBER = 4;
    private volatile java.lang.Object netprofitrose_;
    /**
     * <pre>
     *净利润增长率
     * </pre>
     *
     * <code>string netprofitrose = 4;</code>
     */
    public java.lang.String getNetprofitrose() {
      java.lang.Object ref = netprofitrose_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        netprofitrose_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *净利润增长率
     * </pre>
     *
     * <code>string netprofitrose = 4;</code>
     */
    public com.google.protobuf.ByteString
        getNetprofitroseBytes() {
      java.lang.Object ref = netprofitrose_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        netprofitrose_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getRevenueBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, revenue_);
      }
      if (!getNetprofitBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, netprofit_);
      }
      if (!getRevenueroseBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, revenuerose_);
      }
      if (!getNetprofitroseBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, netprofitrose_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getRevenueBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, revenue_);
      }
      if (!getNetprofitBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, netprofit_);
      }
      if (!getRevenueroseBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, revenuerose_);
      }
      if (!getNetprofitroseBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, netprofitrose_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.yyy.dailycode.enjoycoding.protocolbuffer.vo.FinancialDataModel.FinancialData)) {
        return super.equals(obj);
      }
      com.yyy.dailycode.enjoycoding.protocolbuffer.vo.FinancialDataModel.FinancialData other = (com.yyy.dailycode.enjoycoding.protocolbuffer.vo.FinancialDataModel.FinancialData) obj;

      boolean result = true;
      result = result && getRevenue()
          .equals(other.getRevenue());
      result = result && getNetprofit()
          .equals(other.getNetprofit());
      result = result && getRevenuerose()
          .equals(other.getRevenuerose());
      result = result && getNetprofitrose()
          .equals(other.getNetprofitrose());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + REVENUE_FIELD_NUMBER;
      hash = (53 * hash) + getRevenue().hashCode();
      hash = (37 * hash) + NETPROFIT_FIELD_NUMBER;
      hash = (53 * hash) + getNetprofit().hashCode();
      hash = (37 * hash) + REVENUEROSE_FIELD_NUMBER;
      hash = (53 * hash) + getRevenuerose().hashCode();
      hash = (37 * hash) + NETPROFITROSE_FIELD_NUMBER;
      hash = (53 * hash) + getNetprofitrose().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.yyy.dailycode.enjoycoding.protocolbuffer.vo.FinancialDataModel.FinancialData parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.yyy.dailycode.enjoycoding.protocolbuffer.vo.FinancialDataModel.FinancialData parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.yyy.dailycode.enjoycoding.protocolbuffer.vo.FinancialDataModel.FinancialData parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.yyy.dailycode.enjoycoding.protocolbuffer.vo.FinancialDataModel.FinancialData parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.yyy.dailycode.enjoycoding.protocolbuffer.vo.FinancialDataModel.FinancialData parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.yyy.dailycode.enjoycoding.protocolbuffer.vo.FinancialDataModel.FinancialData parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.yyy.dailycode.enjoycoding.protocolbuffer.vo.FinancialDataModel.FinancialData parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.yyy.dailycode.enjoycoding.protocolbuffer.vo.FinancialDataModel.FinancialData parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.yyy.dailycode.enjoycoding.protocolbuffer.vo.FinancialDataModel.FinancialData parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.yyy.dailycode.enjoycoding.protocolbuffer.vo.FinancialDataModel.FinancialData parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.yyy.dailycode.enjoycoding.protocolbuffer.vo.FinancialDataModel.FinancialData parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.yyy.dailycode.enjoycoding.protocolbuffer.vo.FinancialDataModel.FinancialData parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.yyy.dailycode.enjoycoding.protocolbuffer.vo.FinancialDataModel.FinancialData prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     *财务信息
     * </pre>
     *
     * Protobuf type {@code FinancialData}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:FinancialData)
        com.yyy.dailycode.enjoycoding.protocolbuffer.vo.FinancialDataModel.FinancialDataOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.yyy.dailycode.enjoycoding.protocolbuffer.vo.FinancialDataModel.internal_static_FinancialData_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.yyy.dailycode.enjoycoding.protocolbuffer.vo.FinancialDataModel.internal_static_FinancialData_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.yyy.dailycode.enjoycoding.protocolbuffer.vo.FinancialDataModel.FinancialData.class, com.yyy.dailycode.enjoycoding.protocolbuffer.vo.FinancialDataModel.FinancialData.Builder.class);
      }

      // Construct using com.yyy.dailycode.enjoycoding.protocolbuffer.vo.FinancialDataModel.FinancialData.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        revenue_ = "";

        netprofit_ = "";

        revenuerose_ = "";

        netprofitrose_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.yyy.dailycode.enjoycoding.protocolbuffer.vo.FinancialDataModel.internal_static_FinancialData_descriptor;
      }

      public com.yyy.dailycode.enjoycoding.protocolbuffer.vo.FinancialDataModel.FinancialData getDefaultInstanceForType() {
        return com.yyy.dailycode.enjoycoding.protocolbuffer.vo.FinancialDataModel.FinancialData.getDefaultInstance();
      }

      public com.yyy.dailycode.enjoycoding.protocolbuffer.vo.FinancialDataModel.FinancialData build() {
        com.yyy.dailycode.enjoycoding.protocolbuffer.vo.FinancialDataModel.FinancialData result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.yyy.dailycode.enjoycoding.protocolbuffer.vo.FinancialDataModel.FinancialData buildPartial() {
        com.yyy.dailycode.enjoycoding.protocolbuffer.vo.FinancialDataModel.FinancialData result = new com.yyy.dailycode.enjoycoding.protocolbuffer.vo.FinancialDataModel.FinancialData(this);
        result.revenue_ = revenue_;
        result.netprofit_ = netprofit_;
        result.revenuerose_ = revenuerose_;
        result.netprofitrose_ = netprofitrose_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.yyy.dailycode.enjoycoding.protocolbuffer.vo.FinancialDataModel.FinancialData) {
          return mergeFrom((com.yyy.dailycode.enjoycoding.protocolbuffer.vo.FinancialDataModel.FinancialData)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.yyy.dailycode.enjoycoding.protocolbuffer.vo.FinancialDataModel.FinancialData other) {
        if (other == com.yyy.dailycode.enjoycoding.protocolbuffer.vo.FinancialDataModel.FinancialData.getDefaultInstance()) return this;
        if (!other.getRevenue().isEmpty()) {
          revenue_ = other.revenue_;
          onChanged();
        }
        if (!other.getNetprofit().isEmpty()) {
          netprofit_ = other.netprofit_;
          onChanged();
        }
        if (!other.getRevenuerose().isEmpty()) {
          revenuerose_ = other.revenuerose_;
          onChanged();
        }
        if (!other.getNetprofitrose().isEmpty()) {
          netprofitrose_ = other.netprofitrose_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.yyy.dailycode.enjoycoding.protocolbuffer.vo.FinancialDataModel.FinancialData parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.yyy.dailycode.enjoycoding.protocolbuffer.vo.FinancialDataModel.FinancialData) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object revenue_ = "";
      /**
       * <pre>
       *营业收入
       * </pre>
       *
       * <code>string revenue = 1;</code>
       */
      public java.lang.String getRevenue() {
        java.lang.Object ref = revenue_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          revenue_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *营业收入
       * </pre>
       *
       * <code>string revenue = 1;</code>
       */
      public com.google.protobuf.ByteString
          getRevenueBytes() {
        java.lang.Object ref = revenue_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          revenue_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *营业收入
       * </pre>
       *
       * <code>string revenue = 1;</code>
       */
      public Builder setRevenue(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        revenue_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *营业收入
       * </pre>
       *
       * <code>string revenue = 1;</code>
       */
      public Builder clearRevenue() {
        
        revenue_ = getDefaultInstance().getRevenue();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *营业收入
       * </pre>
       *
       * <code>string revenue = 1;</code>
       */
      public Builder setRevenueBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        revenue_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object netprofit_ = "";
      /**
       * <pre>
       *净利润
       * </pre>
       *
       * <code>string netprofit = 2;</code>
       */
      public java.lang.String getNetprofit() {
        java.lang.Object ref = netprofit_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          netprofit_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *净利润
       * </pre>
       *
       * <code>string netprofit = 2;</code>
       */
      public com.google.protobuf.ByteString
          getNetprofitBytes() {
        java.lang.Object ref = netprofit_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          netprofit_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *净利润
       * </pre>
       *
       * <code>string netprofit = 2;</code>
       */
      public Builder setNetprofit(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        netprofit_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *净利润
       * </pre>
       *
       * <code>string netprofit = 2;</code>
       */
      public Builder clearNetprofit() {
        
        netprofit_ = getDefaultInstance().getNetprofit();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *净利润
       * </pre>
       *
       * <code>string netprofit = 2;</code>
       */
      public Builder setNetprofitBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        netprofit_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object revenuerose_ = "";
      /**
       * <pre>
       *营业收入增长率
       * </pre>
       *
       * <code>string revenuerose = 3;</code>
       */
      public java.lang.String getRevenuerose() {
        java.lang.Object ref = revenuerose_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          revenuerose_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *营业收入增长率
       * </pre>
       *
       * <code>string revenuerose = 3;</code>
       */
      public com.google.protobuf.ByteString
          getRevenueroseBytes() {
        java.lang.Object ref = revenuerose_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          revenuerose_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *营业收入增长率
       * </pre>
       *
       * <code>string revenuerose = 3;</code>
       */
      public Builder setRevenuerose(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        revenuerose_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *营业收入增长率
       * </pre>
       *
       * <code>string revenuerose = 3;</code>
       */
      public Builder clearRevenuerose() {
        
        revenuerose_ = getDefaultInstance().getRevenuerose();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *营业收入增长率
       * </pre>
       *
       * <code>string revenuerose = 3;</code>
       */
      public Builder setRevenueroseBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        revenuerose_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object netprofitrose_ = "";
      /**
       * <pre>
       *净利润增长率
       * </pre>
       *
       * <code>string netprofitrose = 4;</code>
       */
      public java.lang.String getNetprofitrose() {
        java.lang.Object ref = netprofitrose_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          netprofitrose_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *净利润增长率
       * </pre>
       *
       * <code>string netprofitrose = 4;</code>
       */
      public com.google.protobuf.ByteString
          getNetprofitroseBytes() {
        java.lang.Object ref = netprofitrose_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          netprofitrose_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *净利润增长率
       * </pre>
       *
       * <code>string netprofitrose = 4;</code>
       */
      public Builder setNetprofitrose(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        netprofitrose_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *净利润增长率
       * </pre>
       *
       * <code>string netprofitrose = 4;</code>
       */
      public Builder clearNetprofitrose() {
        
        netprofitrose_ = getDefaultInstance().getNetprofitrose();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *净利润增长率
       * </pre>
       *
       * <code>string netprofitrose = 4;</code>
       */
      public Builder setNetprofitroseBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        netprofitrose_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:FinancialData)
    }

    // @@protoc_insertion_point(class_scope:FinancialData)
    private static final com.yyy.dailycode.enjoycoding.protocolbuffer.vo.FinancialDataModel.FinancialData DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.yyy.dailycode.enjoycoding.protocolbuffer.vo.FinancialDataModel.FinancialData();
    }

    public static com.yyy.dailycode.enjoycoding.protocolbuffer.vo.FinancialDataModel.FinancialData getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<FinancialData>
        PARSER = new com.google.protobuf.AbstractParser<FinancialData>() {
      public FinancialData parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new FinancialData(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<FinancialData> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<FinancialData> getParserForType() {
      return PARSER;
    }

    public com.yyy.dailycode.enjoycoding.protocolbuffer.vo.FinancialDataModel.FinancialData getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_FinancialData_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_FinancialData_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023FinancialData.proto\"_\n\rFinancialData\022\017" +
      "\n\007revenue\030\001 \001(\t\022\021\n\tnetprofit\030\002 \001(\t\022\023\n\013re" +
      "venuerose\030\003 \001(\t\022\025\n\rnetprofitrose\030\004 \001(\tBE" +
      "\n/com.yyy.dailycode.enjoycoding.protocol" +
      "buffer.voB\022FinancialDataModelb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_FinancialData_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_FinancialData_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_FinancialData_descriptor,
        new java.lang.String[] { "Revenue", "Netprofit", "Revenuerose", "Netprofitrose", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
